version: '3.3'
services:
  node:
    image: devmtl/resilio:2.7.1
    environment:
      RSLSYNC_SECRET: AOAY73WGERIAAH5RPN6TAUDMPDCZLSKQF
    ports:
     - 33333
    volumes:
     - /home/admin/storage:/data
    networks:
     - proxy
    logging:
      driver: json-file
    deploy:
      restart_policy:
        max_attempts: 20
      placement:
        constraints:
         - node.role == worker
      resources:
        reservations:
          memory: 192M
        limits:
          cpus: '0.333'
          memory: 512M

networks:
  proxy:
    external: true