version: "3.7"
services:
  node0:
    image: minio/minio
    command: server /export
    volumes:
      - type: bind
        source: /home/admin/storage
        target: /export
    ports:
      - 9000
    networks:
      - proxy
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    deploy:
      labels:
        #### Labels define the behavior and rules of the traefik proxy for this container ####
        #### Labels define the behavior and rules of the traefik proxy for this container ####
        - traefik.enable=true # <== Enable traefik on itself to view dashboard and assign subdomain to view it
        - traefik.tags=public
        - traefik.docker.network=proxy
        - traefik.http.routers.minio-secured.entrypoints=web-secured
        - traefik.http.routers.minio-secured.rule=Host(`cdn.${HOST}`) # <== Setting the domain for the dashboard 
        
        - traefik.http.routers.minio-secured.tls=true
        - traefik.http.routers.minio-secured.tls.certresolver=mytlschallenge
                   
        - traefik.http.services.minio.loadbalancer.server.port=9000
      placement:
        constraints:
         - node.role == worker
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
   proxy:
     external: true

secrets:
  secret_key:
    external: true
  access_key:
    external: true